<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Zainaya" failures="3" tests="16" name="edgeTest" time="174.846" errors="0" timestamp="2025-05-19T18:29:26 PDT">
  <testcase classname="testCases.TC01_LaunchApplication" name="testLaunchApplication" time="0.058"/>
  <testcase classname="testCases.TC03_AddToCart" name="testAddToCart" time="8.516"/>
  <testcase classname="testCases.TC05_AddToWishList" name="testAddToWishList" time="2.76">
    <skipped/>
  </testcase> <!-- testAddToWishList -->
  <testcase classname="testCases.TC05_AddToWishList" name="testAddToWishList" time="10.29">
    <skipped/>
  </testcase> <!-- testAddToWishList -->
  <testcase classname="testCases.TC05_AddToWishList" name="testAddToWishList" time="10.771">
    <failure type="java.lang.AssertionError" message="Test failed due to unexpected exception.">
      <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at testCases.TC05_AddToWishList.testAddToWishList(TC05_AddToWishList.java:68)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testAddToWishList -->
  <testcase classname="testCases.TC06_AddAffiliate" name="testAddAffiliate" time="2.619">
    <skipped/>
  </testcase> <!-- testAddAffiliate -->
  <testcase classname="testCases.TC06_AddAffiliate" name="testAddAffiliate" time="10.46">
    <skipped/>
  </testcase> <!-- testAddAffiliate -->
  <testcase classname="testCases.TC06_AddAffiliate" name="testAddAffiliate" time="11.697">
    <failure type="java.lang.AssertionError" message="Test failed due to unexpected exception.">
      <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at testCases.TC06_AddAffiliate.testAddAffiliate(TC06_AddAffiliate.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testAddAffiliate -->
  <testcase classname="testCases.TC02_Login" name="testLogin" time="2.723"/>
  <testcase classname="testCases.TC02_Login" name="testLogin" time="1.705"/>
  <testcase classname="testCases.TC02_Login" name="testLogin" time="1.742"/>
  <testcase classname="testCases.TC02_Login" name="testLogin" time="1.845"/>
  <testcase classname="testCases.TC02_Login" name="testLogin" time="2.045"/>
  <testcase classname="testCases.TC04_CompletePurchase" name="testCompletePurchase" time="9.852">
    <skipped/>
  </testcase> <!-- testCompletePurchase -->
  <testcase classname="testCases.TC04_CompletePurchase" name="testCompletePurchase" time="12.377">
    <skipped/>
  </testcase> <!-- testCompletePurchase -->
  <testcase classname="testCases.TC04_CompletePurchase" name="testCompletePurchase" time="12.36">
    <failure type="java.lang.AssertionError" message="Test failed due to unexpected exception.">
      <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at testCases.TC04_CompletePurchase.testCompletePurchase(TC04_CompletePurchase.java:81)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testCompletePurchase -->
</testsuite> <!-- edgeTest -->
