<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Zainaya" failures="1" tests="5" name="testCases.TC05_AddToWishList" time="37.218" errors="0" timestamp="2025-05-19T18:29:27 PDT" skipped="2">
  <testcase classname="testCases.TC05_AddToWishList" name="testAddToWishList" time="10.771">
    <failure message="Test failed due to unexpected exception." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC05_AddToWishList.testAddToWishList(TC05_AddToWishList.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- testAddToWishList -->
  <testcase classname="testCases.TC05_AddToWishList" name="testAddToWishList" time="2.760">
    <skipped/>
  </testcase> <!-- testAddToWishList -->
  <testcase classname="testCases.TC05_AddToWishList" name="testAddToWishList" time="6.668"/>
  <testcase classname="testCases.TC05_AddToWishList" name="testAddToWishList" time="6.729"/>
  <testcase classname="testCases.TC05_AddToWishList" name="testAddToWishList" time="10.290">
    <skipped/>
  </testcase> <!-- testAddToWishList -->
</testsuite> <!-- testCases.TC05_AddToWishList -->
